/*
 * AdminGUI.java
 *
 * Created on __DATE__, __TIME__
 */

package com.gui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.model.AdminModel;

/**
 * 
 * @author JIAZHEN XIE
 */
public class AdminLogin extends javax.swing.JFrame {

	private AdminModel adminModel;

	/** Creates new form AdminGUI */
	public AdminLogin(AdminModel adminModel) {
		this.adminModel = adminModel;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		loginBtn = new javax.swing.JButton();
		clearBtn = new javax.swing.JButton();
		languageBtn = new javax.swing.JButton();
		accountLabel = new javax.swing.JLabel();
		passwordLabel = new javax.swing.JLabel();
		accountText = new javax.swing.JTextField();
		passwordText = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/images/banner.png"))); // NOI18N

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/images/face.png"))); // NOI18N

		jPanel1.setBackground(new java.awt.Color(51, 153, 255));

		loginBtn.setFont(new java.awt.Font("新宋体", 0, 12));
		loginBtn.setText("\u767b\u5f55");
		loginBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loginBtnActionPerformed(evt);
			}
		});

		clearBtn.setFont(new java.awt.Font("新宋体", 0, 12));
		clearBtn.setText("\u91cd\u7f6e");
		clearBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				clearBtnActionPerformed(evt);
			}
		});

		languageBtn.setFont(new java.awt.Font("新宋体", 0, 12));
		languageBtn.setText("English");
		languageBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				languageBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(135, Short.MAX_VALUE)
										.addComponent(languageBtn)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(clearBtn)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(loginBtn)
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(loginBtn)
														.addComponent(clearBtn)
														.addComponent(
																languageBtn))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		accountLabel.setFont(new java.awt.Font("宋体", 0, 14));
		accountLabel.setText("\u8d26\u53f7:");

		passwordLabel.setFont(new java.awt.Font("宋体", 0, 14));
		passwordLabel.setText("\u5bc6\u7801:");

		accountText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				accountTextActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jLabel2)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														accountLabel,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														passwordLabel,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														54, Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(passwordText, 0,
														0, Short.MAX_VALUE)
												.addComponent(
														accountText,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														128, Short.MAX_VALUE)))
				.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel2)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						accountLabel,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						28,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						accountText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						passwordLabel,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						27,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						passwordText,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(21, 21,
																		21)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		char[] inputPW = passwordText.getPassword();
		String password = new String(inputPW);
		String account = accountText.getText();
		if (password.isEmpty() || account.isEmpty()) {
			JOptionPane.showMessageDialog(null,
					"You must enter your account and password!");
		} else {

			if (adminModel.permitLogin(account, password)) {
				System.out.println("correct");
			} else {
				JOptionPane.showMessageDialog(null,
						"Username or Password is not correct!");
			}

			// int result = adminModel.login(username, password);
			// // login repeat
			// if (result == 0) {
			// JOptionPane.showMessageDialog(null,
			// "This user has already online!");
			// } // username or PW incorrect
			// else if (result == 1) {
			// JOptionPane.showMessageDialog(null,
			// "Username or Password is not correct!");
			// } // login successfully
			// else if (result == 2) {
			//
			// }
		}

	}

	private void languageBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (adminModel.isChinese()) {
			accountLabel.setText("Account:");
			passwordLabel.setText("Password:");
			languageBtn.setText("中文");
			clearBtn.setText("Reset");
			loginBtn.setText("Login");
			adminModel.setChinese(false);
		} else {
			accountLabel.setText("账号:");
			passwordLabel.setText("密码:");
			languageBtn.setText("English");
			clearBtn.setText("重置");
			loginBtn.setText("登录");
			adminModel.setChinese(true);
		}

	}

	private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		passwordText.setText("");
		accountText.setText("");

	}

	private void accountTextActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				AdminModel adminModel = new AdminModel();
				JFrame adminLogin = new AdminLogin(adminModel);
				adminLogin.setLocationRelativeTo(null);
				adminLogin.setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel accountLabel;
	private javax.swing.JTextField accountText;
	private javax.swing.JButton clearBtn;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JButton languageBtn;
	private javax.swing.JButton loginBtn;
	private javax.swing.JLabel passwordLabel;
	private javax.swing.JPasswordField passwordText;
	// End of variables declaration//GEN-END:variables

}